### ISSUE TITLE
GetTypeFromHandleUnsafe method not found on .NET Core 3.1+ Linux

### ISSUE THREAD

**Issue by MSDN-WhiteKnight** [MSDN-WhiteKnight/CilTools#49]
**netstd.yml**

```
name: .NET Standard

on: [push]

jobs:
  NetStd-CI:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.100'
    - name: Build with dotnet
      run: dotnet build CilTools.Metadata/CilTools.Metadata.csproj -f netstandard2.0
    - name: Build tests with dotnet
      run: dotnet build tests/CilTools.BytecodeAnalysis.Tests.NetCore/CilTools.BytecodeAnalysis.Tests.NetCore.csproj
    - name: Test
      run: dotnet test tests/CilTools.BytecodeAnalysis.Tests.NetCore/CilTools.BytecodeAnalysis.Tests.NetCore.csproj -f netcoreapp3.1
    - name: Archive build results
      uses: actions/upload-artifact@v1
      with:
          name: Output
          path: CilTools.Metadata/bin/Debug/
```

**CilTools.BytecodeAnalysis.Tests.NetCore.csproj**

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <Authors>MSDN-WhiteKnight</Authors>
    <Company>CIL Tools</Company>
    <Product>CIL Tools</Product>
    <Copyright>Copyright (c) 2020, MSDN.WhiteKnight</Copyright>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.5.0" />
    <PackageReference Include="MSTest.TestAdapter" Version="2.1.0" />
    <PackageReference Include="MSTest.TestFramework" Version="2.1.0" />
    <PackageReference Include="coverlet.collector" Version="1.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\CilTools.BytecodeAnalysis\CilTools.BytecodeAnalysis.csproj" />
    <ProjectReference Include="..\CilTools.Tests.Common\CilTools.Tests.Common.csproj" />
  </ItemGroup>

</Project>
```
----
**Error:**

>System.MissingMethodException: GetTypeFromHandleUnsafe is not found
>   at CilTools.Reflection.ModuleWrapperDynamic.ResolveMember(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments) in /home/runner/work/CilTools/CilTools/CilTools.BytecodeAnalysis/Reflection/ModuleWrapperDynamic.cs:line 278
>    at CilTools.BytecodeAnalysis.CilInstruction.ResolveMemberToken(Int32 token) in /home/runner/work/CilTools/CilTools/CilTools.BytecodeAnalysis/CilInstruction.cs:line 248
>    at CilTools.BytecodeAnalysis.CilTokenInstruction.get_ReferencedMember() in /home/runner/work/CilTools/CilTools/CilTools.BytecodeAnalysis/CilTokenInstruction.cs:line 39
